spring:
  profiles:
    active:
    - dev
---
server:
  prot: 8021
spring:
  profiles: dev
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  prot: 8022
spring:
  profiles: test
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
